<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class acc_expenses extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('acc_expenses_model');
        $this->load->model('acc_expensesItem_model');
        $this->load->model('acc_expensesType_model');
        $this->load->model('Location_model');
    } 

    /*
     * Listing of expenses
     */
    function index()
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('read',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$user = $this->User_model->get('person_id', $id);
			unset($user['password']);
			$user_role = $this->User_model->loadRoles($user['person_id']);
			
			$this->data['user'] = $user['username'];
			$this->data['urole'] = $user_role;
			$specialPerm =  $this->User_model->loadSpecialPermission($id);
					
			
			$this->data['pp'] = $specialPerm;
			$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
			
			if($this->User_model->hasPermission('WILD_CARD',$id)){
				$this->data['expenses'] = $this->acc_expenses_model->get_all_acc_expenses();
			}
			else{
				$this->data['expenses'] = $this->acc_expenses_model->get_location_acc_expenses($user['location_id']);
			}
			
			$this->data['expenseSubtype'] = $this->acc_expensesType_model->get_all_expenseSubtype();
			$this->data['expenseItem'] = $this->acc_expensesItem_model->get_all_acc_expense_items();
			
			$this->data['location'] = $this->Location_model->get_all_location();
			
			
			$this->template
				->title('Welcome','My Aapp')
				->build('acc_expenses/index',$this->data);
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
        
    }

    /*
     * Adding a new expense
     */
    function add()
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			$user = $this->User_model->get('person_id', $id);
				unset($user['password']);
			
			if(!($this->User_model->hasPermission('add',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			
				// $this->form_validation->set_rules('location_id', '<b>Location</b>', 'trim|required');
				// $this->form_validation->set_rules('amount', '<b>Amount</b>','trim|required|integer|min_length[1]|max_length[4]');
				$this->form_validation->set_rules('dtp_input2', '<b>Date</b>', 'trim|required');
				
			if(isset($_POST) && count($_POST) > 0 && $this->form_validation->run())     
			{     
				list($part1,$part2) = explode(' ', date("Y-m-d H:i:s",strtotime($this->input->post('dtp_input2'))));
				list($year, $month, $day) = explode('-', $part1);
				list($hours, $minutes,$seconds) = explode(':', $part2);
				$timeto =  mktime($hours, $minutes, $seconds, $month, $day, $year);
				//echo $timeto;
				$params = array(
					'location_id' => $this->input->post('location_id'),
					'acc_expense_item_id' => $this->input->post('expenseItem_id'),
					'expense' => $this->input->post('amount'),
					'date' => $timeto,
					'remark' => $this->input->post('remark'),
					);
				// $release_date=$_POST['dtp_input2'];
				//echo date("Y-m-d H:i:s",strtotime($release_date));
				// print_r($params);
				$expense_id = $this->acc_expenses_model->add_acc_expenses($params);
				redirect('acc_expenses/index');
			}else{
				
				$user_role = $this->User_model->loadRoles($user['person_id']);
				
				$this->data['user'] = $user['username'];
				$this->data['urole'] = $user_role;
				$specialPerm =  $this->User_model->loadSpecialPermission($id);
						
				
				$this->data['pp'] = $specialPerm;
				$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
				$this->data['expenses'] = $this->acc_expenses_model->get_all_acc_expenses();
				$this->data['expenseItem'] = $this->acc_expensesItem_model->get_all_acc_expense_items();
				$this->data['location'] = $this->Location_model->get_all_location();
				
				
				$this->template
					->title('Welcome','My Aapp')
					->build('acc_expenses/add',$this->data);
			}
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
       
    }  

    /*
     * Editing a expense
     */
    function edit($expenses_id)
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			
			if(!($this->User_model->hasPermission('update',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			// check if the expense exists before trying to edit it
			$this->data['expense'] = $this->acc_expenses_model->get_acc_expense($expenses_id);
			$this->data['location'] = $this->Location_model->get_all_location();
			
			if(isset($this->data['expense']['id']))
			{
				
				$this->form_validation->set_rules('expenseItem_id', '<b>Item</b>', 'trim|required|integer|min_length[1]|max_length[100]');
				$this->form_validation->set_rules('amount', '<b>Amount</b>', 'trim|required|integer|min_length[1]|max_length[10]');
					
				if(isset($_POST) && count($_POST) > 0 && $this->form_validation->run())     
				{      
					$params = array(
						
						'acc_expense_item_id' => $this->input->post('expenseItem_id'),
						'expense' => $this->input->post('amount'),
						'remark' => $this->input->post('remark'),
					);
					
					$this->acc_expenses_model->update_acc_expense($expenses_id,$params);            
					redirect('acc_expenses/index');
				}
				else
				{
					$user = $this->User_model->get('person_id', $id);
					unset($user['password']);
					$user_role = $this->User_model->loadRoles($user['person_id']);
					
					$this->data['user'] = $user['username'];
					$this->data['urole'] = $user_role;
					$specialPerm =  $this->User_model->loadSpecialPermission($id);
							
					
					$this->data['pp'] = $specialPerm;
					$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
					$this->data['expenseItem'] = $this->acc_expensesItem_model->get_all_acc_expense_items();
					
					
					$this->template
						->title('Welcome','My Aapp')
						->build('acc_expenses/edit',$this->data);
				}
			}
			else
				show_error('The expense you are trying to edit does not exist.');
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    } 

    /*
     * Deleting expense
     */
    function remove($expenses_id)
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			
			if(!($this->User_model->hasPermission('delete',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$expense = $this->acc_expenses_model->get_expense($expenses_id);

			// check if the expense exists before trying to delete it
			if(isset($expense['id']))
			{
				$this->acc_expenses_model->delete_expense($expenses_id);
				redirect('acc_expenses/index');
			}
			else
				show_error('The expense you are trying to delete does not exist.');
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    }
    
}
