<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class acc_master_expense_types extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Acc_expensesType_model');
    } 

    /*
     * Listing of expensess
     */
    function index()
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('read',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$user = $this->User_model->get('person_id', $id);
			unset($user['password']);
			$user_role = $this->User_model->loadRoles($user['person_id']);
			
			$this->data['user'] = $user['username'];
			$this->data['urole'] = $user_role;
			$specialPerm =  $this->User_model->loadSpecialPermission($id);
					
			
			$this->data['pp'] = $specialPerm;
			$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
			$this->data['expenseType'] = $this->Acc_expensesType_model->get_all_expenseType();
			
			
			$this->template
				->title('Welcome','My Aapp')
				->build('acc_master_expense_types/index',$this->data);
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
        
    }

    /*
     * Adding a new expenses
     */
    function add()
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			$user = $this->User_model->get('person_id', $id);
				unset($user['password']);
			
			if(!($this->User_model->hasPermission('add',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			
				
				
			if(isset($_POST) && count($_POST) > 0 )     
			{     
				
				$params = array(
						'name' => $this->input->post('expenseType'),
						'description' => $this->input->post('expenseDescription'),
					
					);
				$this->Acc_expensesType_model->add_expenseType($params);            
				redirect('Acc_master_expense_types/index');
			}else{
				
				$user_role = $this->User_model->loadRoles($user['person_id']);
				
				$this->data['user'] = $user['username'];
				$this->data['urole'] = $user_role;
				$specialPerm =  $this->User_model->loadSpecialPermission($id);
						
				
				$this->data['pp'] = $specialPerm;
				$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
				$this->data['expenseType'] = $this->Acc_expensesType_model->get_all_expenseType();
				
				$this->template
					->title('Welcome','My Aapp')
					->build('acc_master_expense_types/add',$this->data);
			}
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
       
    }  

    /*
     * Editing a expenses
     */
    function edit($expenses_id)
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			
			if(!($this->User_model->hasPermission('update',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			// check if the ExpenseSubtype exists before trying to edit it
			$this->data['expenseType'] = $this->Acc_expensesType_model->get_expenseType($expenses_id);
			
			if(isset($this->data['expenseType']['id']))
			{
				
				$this->form_validation->set_rules('expenseType', '<b>Name</b>', 'trim|required|min_length[1]|max_length[10]');
				$this->form_validation->set_rules('expenseDescription', '<b>Description</b>', 'trim|min_length[0]|max_length[400]');
					
					
				if(isset($_POST) && count($_POST) > 0 && $this->form_validation->run())     
				{      
					$params = array(
						
						'name' => $this->input->post('expenseType'),
						'description' => $this->input->post('expenseDescription'),
					
					);
					
					$this->Acc_expensesType_model->update_expenseType($expenses_id,$params);            
					redirect('Acc_master_expense_types/index');
				}
				else
				{
					$user = $this->User_model->get('person_id', $id);
					unset($user['password']);
					$user_role = $this->User_model->loadRoles($user['person_id']);
					
					$this->data['user'] = $user['username'];
					$this->data['urole'] = $user_role;
					$specialPerm =  $this->User_model->loadSpecialPermission($id);
							
					
					$this->data['pp'] = $specialPerm;
					$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
					
					
					$this->template
						->title('Welcome','My Aapp')
						->build('Acc_master_expense_types/edit',$this->data);
				}
			}
			else
				show_error('The expenses you are trying to edit does not exist.');
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    } 

    /*
     * Deleting expenses
     */
    function remove($expenses_id)
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			
			if(!($this->User_model->hasPermission('delete',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$expenses = $this->Acc_expensesType_model->get_expenseType($expenses_id);
			

			// check if the expenses exists before trying to delete it
			if(isset($expenses['id']))
			{
				$this->Acc_expensesType_model->delete_expenseType($expenses_id);
				redirect('Acc_master_expense_types/index');
			}
			else
				show_error('The expenses type you are trying to delete does not exist.');
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    }
    
}
