<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class acc_master_sale_types extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Acc_salesType_model');
    } 

    /*
     * Listing of sales
     */
    function index()
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('read',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$user = $this->User_model->get('person_id', $id);
			unset($user['password']);
			$user_role = $this->User_model->loadRoles($user['person_id']);
			
			$this->data['user'] = $user['username'];
			$this->data['urole'] = $user_role;
			$specialPerm =  $this->User_model->loadSpecialPermission($id);
					
			
			$this->data['pp'] = $specialPerm;
			$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
			
			
			$this->data['saleType'] = $this->Acc_salesType_model->get_all_saleType();
			
			
			$this->template
				->title('Welcome','My Aapp')
				->build('acc_master_sale_types/index',$this->data);
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
        
    }

    /*
     * Adding a new sale
     */
    function add()
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			$user = $this->User_model->get('person_id', $id);
				unset($user['password']);
			
			if(!($this->User_model->hasPermission('add',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			
			if(isset($_POST) && count($_POST) > 0 )     
			{     
				
				$params = array(
						'name' => $this->input->post('saleType'),
						'description' => $this->input->post('saleDescription'),
					
					);
				$this->Acc_salesType_model->add_saleType($params);            
				redirect('acc_master_sale_types/index');
			}else{
				
				$user_role = $this->User_model->loadRoles($user['person_id']);
				
				$this->data['user'] = $user['username'];
				$this->data['urole'] = $user_role;
				$specialPerm =  $this->User_model->loadSpecialPermission($id);
						
				
				$this->data['pp'] = $specialPerm;
				$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
				$this->data['saleType'] = $this->Acc_salesType_model->get_all_saleType();
			
				$this->template
					->title('Welcome','My Aapp')
					->build('acc_master_sale_types/add',$this->data);
			}
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
       
    }  

    /*
     * Editing a sale
     */
    function edit($sales_id)
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			
			if(!($this->User_model->hasPermission('update',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			// check if the sale exists before trying to edit it
			$this->data['sale'] = $this->Acc_sales_model->get_sale($sales_id);
			$this->data['location'] = $this->Location_model->get_all_location();
			
			if(isset($this->data['sale']['id']))
			{
				
				$this->form_validation->set_rules('amount', '<b>Amount</b>', 'trim|required|integer|min_length[1]|max_length[10]');
					
				if(isset($_POST) && count($_POST) > 0 && $this->form_validation->run())     
				{      
					$params = array(
						
						'acc_salesType_id' => $this->input->post('salesType_id'),
						'sale' => $this->input->post('amount'),
						'remark' => $this->input->post('remark'),
					);
					
					$this->Acc_sales_model->update_sale($sales_id,$params);            
					redirect('acc_sales/index');
				}
				else
				{
					$user = $this->User_model->get('person_id', $id);
					unset($user['password']);
					$user_role = $this->User_model->loadRoles($user['person_id']);
					
					$this->data['user'] = $user['username'];
					$this->data['urole'] = $user_role;
					$specialPerm =  $this->User_model->loadSpecialPermission($id);
							
					
					$this->data['pp'] = $specialPerm;
					$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
					$this->data['product'] = $this->Product_model->get_all_product();
					$this->data['unit'] = $this->Unit_model->get_all_units();
					$this->data['saleType'] = $this->Acc_salesType_model->get_all_saleType();
					
					
					$this->template
						->title('Welcome','My Aapp')
						->build('acc_sales/edit',$this->data);
				}
			}
			else
				show_error('The sale you are trying to edit does not exist.');
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    } 

    /*
     * Deleting sale
     */
    function remove($sales_id)
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			
			if(!($this->User_model->hasPermission('delete',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$sale = $this->Acc_sales_model->get_sale($sales_id);

			// check if the sale exists before trying to delete it
			if(isset($sale['id']))
			{
				$this->Acc_sales_model->delete_sale($sales_id);
				redirect('acc_sales/index');
			}
			else
				show_error('The sale you are trying to delete does not exist.');
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    }
    
}
