<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class acc_master_expense_items extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Acc_expensesType_model');
        $this->load->model('Acc_expensesItem_model');
    } 

    /*
     * Listing of items
     */
    function index()
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('read',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$user = $this->User_model->get('person_id', $id);
			unset($user['password']);
			$user_role = $this->User_model->loadRoles($user['person_id']);
			
			$this->data['user'] = $user['username'];
			$this->data['urole'] = $user_role;
			$specialPerm =  $this->User_model->loadSpecialPermission($id);
					
			
			$this->data['pp'] = $specialPerm;
			$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
			
			
			$this->data['expenseSubtype'] = $this->Acc_expensesType_model->get_all_expenseSubtype();
			$this->data['expenseItem'] = $this->Acc_expensesItem_model->get_all_acc_expense_items();
			
			
			$this->template
				->title('Welcome','My Aapp')
				->build('acc_master_expense_items/index',$this->data);
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
        
    }

    /*
     * Adding a new item
     */
    function add()
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			$user = $this->User_model->get('person_id', $id);
				unset($user['password']);
			
			if(!($this->User_model->hasPermission('add',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			
				
				
			if(isset($_POST) && count($_POST) > 0)     
			{     
				
				$params = array(
					'name' => $this->input->post('expenseItem'),
					'acc_expense_sub_type_id' => $this->input->post('expenseSubtype_id'),
					'description' => $this->input->post('expenseDescription'),
					);
				$this->Acc_expensesItem_model->add_expense_items($params);
				redirect('acc_master_expense_items/index');
			}else{
				
				$user_role = $this->User_model->loadRoles($user['person_id']);
				
				$this->data['user'] = $user['username'];
				$this->data['urole'] = $user_role;
				$specialPerm =  $this->User_model->loadSpecialPermission($id);
						
				
				$this->data['pp'] = $specialPerm;
				$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
				$this->data['expenseSubtype'] = $this->Acc_expensesType_model->get_all_expenseSubtype();
				
				
				$this->template
					->title('Welcome','My Aapp')
					->build('acc_master_expense_items/add',$this->data);
			}
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
       
    }  

    /*
     * Editing a item
     */
    function edit($item_id)
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			
			if(!($this->User_model->hasPermission('update',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			// check if the item exists before trying to edit it
			$this->data['expenseItem'] = $this->Acc_expensesItem_model->get_expense_item($item_id);
			
			if(isset($this->data['expenseItem']['id']))
			{
				
				$this->form_validation->set_rules('expenseItem', '<b>Name</b>', 'trim|required|min_length[1]|max_length[100]');
				$this->form_validation->set_rules('expenseSubtype_id', '<b>Expense Subtype</b>', 'trim|required|integer|min_length[1]|max_length[10]');
				$this->form_validation->set_rules('expenseDescription', '<b>Description</b>', 'trim|min_length[0]|max_length[10]');
					
				if(isset($_POST) && count($_POST) > 0 && $this->form_validation->run())     
				{      
					$params = array(
						
						'name' => $this->input->post('expenseItem'),
						'acc_expense_sub_type_id' => $this->input->post('expenseSubtype_id'),
						'description' => $this->input->post('expenseDescription'),
					);
					
					$this->Acc_expensesItem_model->update_expense_item($item_id,$params);            
					redirect('acc_master_expense_items/index');
				}
				else
				{
					$user = $this->User_model->get('person_id', $id);
					unset($user['password']);
					$user_role = $this->User_model->loadRoles($user['person_id']);
					
					$this->data['user'] = $user['username'];
					$this->data['urole'] = $user_role;
					$specialPerm =  $this->User_model->loadSpecialPermission($id);
							
					
					$this->data['pp'] = $specialPerm;
					$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
					$this->data['expenseSubtype'] = $this->Acc_expensesType_model->get_all_expenseSubtype();
					
					
					$this->template
						->title('Welcome','My Aapp')
						->build('acc_master_expense_items/edit',$this->data);
				}
			}
			else
				show_error('The item you are trying to edit does not exist.');
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    } 

    /*
     * Deleting item
     */
    function remove($item_id)
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			
			if(!($this->User_model->hasPermission('delete',$id)&&($this->User_model->hasPermission('accounts',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$item = $this->Acc_expensesItem_model->get_expense_item($item_id);

			// check if the item exists before trying to delete it
			if(isset($item['id']))
			{
				$this->Acc_expensesItem_model->delete_expense_item($item_id);
				redirect('acc_master_expense_items/index');
			}
			else
				show_error('The item you are trying to delete does not exist.');
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    }
    
}
