<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Autologin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Autologin_model');
    } 

    /*
     * Listing of autologin
     */
    function index()
    {
        $data['autologin'] = $this->Autologin_model->get_all_autologin();
        
        $data['_view'] = 'autologin/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new autologin
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'key' => $this->input->post('key'),
				'created' => $this->input->post('created'),
            );
            
            $autologin_id = $this->Autologin_model->add_autologin($params);
            redirect('autologin/index');
        }
        else
        {            
            $data['_view'] = 'autologin/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a autologin
     */
    function edit($user)
    {   
        // check if the autologin exists before trying to edit it
        $data['autologin'] = $this->Autologin_model->get_autologin($user);
        
        if(isset($data['autologin']['user']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'key' => $this->input->post('key'),
					'created' => $this->input->post('created'),
                );

                $this->Autologin_model->update_autologin($user,$params);            
                redirect('autologin/index');
            }
            else
            {
                $data['_view'] = 'autologin/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The autologin you are trying to edit does not exist.');
    } 

    /*
     * Deleting autologin
     */
    function remove($user)
    {
        $autologin = $this->Autologin_model->get_autologin($user);

        // check if the autologin exists before trying to delete it
        if(isset($autologin['user']))
        {
            $this->Autologin_model->delete_autologin($user);
            redirect('autologin/index');
        }
        else
            show_error('The autologin you are trying to delete does not exist.');
    }
    
}
