<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Location extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Location_model');
		$this->load->model('Division_model');
		
    } 

    /*
     * Listing of location
     */
    function index()
    {
		 if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('read',$id)&&($this->User_model->hasPermission('location',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$user = $this->User_model->get('person_id', $id);
			unset($user['password']);
			
			$user_role = $this->User_model->loadRoles($user['person_id']);
					$this->data['user'] = $user['username'];
					$this->data['role'] = $user_role;
					$specialPerm =  $this->User_model->loadSpecialPermission($id);
					
					$this->data['pp'] = $specialPerm;
					$this->data['location'] = $this->Location_model->get_all_location();
					$this->data['division'] = $this->Division_model->get_all_division();
					$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
					
			$this->template
					->title('Welcome','My Aapp')
					->build('location/index',$this->data);
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    }

    /*
     * Adding a new location
     */
    function add()
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('add',$id)&&($this->User_model->hasPermission('location',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$this->form_validation->set_rules('name', '<b>Name</b>', 'trim|required|min_length[1]|max_length[100]');
			$this->form_validation->set_rules('address', '<b>Address</b>', 'trim|required|min_length[1]|max_length[250]');
			$this->form_validation->set_rules('division_id', '<b>Division Id</b>', 'trim|required');
					
			if(isset($_POST) && count($_POST) > 0 && $this->form_validation->run())
			{   
				$params = array(
					'address' => $this->input->post('address'),
					'name' => $this->input->post('name'),
					'division_id' => $this->input->post('division_id'),
				);
				
				$location_id = $this->Location_model->add_location($params);
				redirect('location/index');
			}
			else
			{            
				
				$user = $this->User_model->get('person_id', $id);
				unset($user['password']);
				
				$user_role = $this->User_model->loadRoles($user['person_id']);
						$this->data['user'] = $user['username'];
						$this->data['role'] = $user_role;
						$specialPerm =  $this->User_model->loadSpecialPermission($id);
						
						$this->data['pp'] = $specialPerm;
						$this->data['division'] = $this->Division_model->get_all_division();
						$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
						
				$this->template
					->title('Welcome','My Aapp')
					->build('location/add',$this->data);
			}
			
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
		
    }  

    /*
     * Editing a location
     */
    function edit($loc_id)
    {   
	
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('update',$id)&&($this->User_model->hasPermission('location',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			// check if the location exists before trying to edit it
			$this->data['location'] = $this->Location_model->get_location($loc_id);
			if(isset($this->data['location']['id']))
			{
				$this->form_validation->set_rules('name', '<b>Name</b>', 'trim|required|min_length[1]|max_length[100]');
				$this->form_validation->set_rules('address', '<b>Address</b>', 'trim|required|min_length[1]|max_length[250]');
				$this->form_validation->set_rules('division_id', '<b>Division Id</b>', 'trim|required');
				if(isset($_POST) && count($_POST) > 0 && $this->form_validation->run()){
				   
					$params = array(
						'address' => $this->input->post('address'),
						'name' => $this->input->post('name'),
						'division_id' => $this->input->post('division_id'),
					);

					$this->Location_model->update_location($loc_id,$params);            
					redirect('location/index');
				}
				else
				{
					
					$user = $this->User_model->get('person_id', $id);
					unset($user['password']);
					
					$user_role = $this->User_model->loadRoles($user['person_id']);
						$this->data['user'] = $user['username'];
						$this->data['role'] = $user_role;
						$specialPerm =  $this->User_model->loadSpecialPermission($id);
						
						$this->data['pp'] = $specialPerm;
						$this->data['division'] = $this->Division_model->get_all_division();
						$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
						
					$this->template
						->title('Welcome','My Aapp')
						->build('location/edit',$this->data);
				}
			}
			else
				show_error('The location you are trying to edit does not exist.');
			
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
       
    } 

    /*
     * Deleting location
     */
    function remove($loc_id)
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('delete',$id)&&($this->User_model->hasPermission('location',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$location = $this->Location_model->get_location($loc_id);

			// check if the location exists before trying to delete it
			if(isset($location['id']))
			{
				$this->Location_model->delete_location($loc_id);
				redirect('location/index');
			}
			else
				show_error('The location you are trying to delete does not exist.');
			}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    }
    
}
