<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Permission extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Permission_model');
    } 

    /*
     * Listing of permission
     */
    function index()
    {
        $data['permission'] = $this->Permission_model->get_all_permission();
        
        $data['_view'] = 'permission/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new permission
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'permission_description' => $this->input->post('permission_description'),
            );
            
            $permission_id = $this->Permission_model->add_permission($params);
            redirect('permission/index');
        }
        else
        {            
            $data['_view'] = 'permission/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a permission
     */
    function edit($permission_id)
    {   
        // check if the permission exists before trying to edit it
        $data['permission'] = $this->Permission_model->get_permission($permission_id);
        
        if(isset($data['permission']['permission_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'permission_description' => $this->input->post('permission_description'),
                );

                $this->Permission_model->update_permission($permission_id,$params);            
                redirect('permission/index');
            }
            else
            {
                $data['_view'] = 'permission/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The permission you are trying to edit does not exist.');
    } 

    /*
     * Deleting permission
     */
    function remove($permission_id)
    {
        $permission = $this->Permission_model->get_permission($permission_id);

        // check if the permission exists before trying to delete it
        if(isset($permission['permission_id']))
        {
            $this->Permission_model->delete_permission($permission_id);
            redirect('permission/index');
        }
        else
            show_error('The permission you are trying to delete does not exist.');
    }
    
}
