<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Person_permission extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Person_permission_model');
    } 

    /*
     * Listing of person_permission
     */
    function index()
    {
        $data['person_permission'] = $this->Person_permission_model->get_all_person_permission();
        
        $data['_view'] = 'person_permission/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new person_permission
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'person_id' => $this->input->post('person_id'),
				'permission_id' => $this->input->post('permission_id'),
            );
            
            $person_permission_id = $this->Person_permission_model->add_person_permission($params);
            redirect('person_permission/index');
        }
        else
        {            
            $data['_view'] = 'person_permission/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a person_permission
     */
    function edit($)
    {   
        // check if the person_permission exists before trying to edit it
        $data['person_permission'] = $this->Person_permission_model->get_person_permission($);
        
        if(isset($data['person_permission']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'person_id' => $this->input->post('person_id'),
					'permission_id' => $this->input->post('permission_id'),
                );

                $this->Person_permission_model->update_person_permission($,$params);            
                redirect('person_permission/index');
            }
            else
            {
                $data['_view'] = 'person_permission/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The person_permission you are trying to edit does not exist.');
    } 

    /*
     * Deleting person_permission
     */
    function remove($)
    {
        $person_permission = $this->Person_permission_model->get_person_permission($);

        // check if the person_permission exists before trying to delete it
        if(isset($person_permission['']))
        {
            $this->Person_permission_model->delete_person_permission($);
            redirect('person_permission/index');
        }
        else
            show_error('The person_permission you are trying to delete does not exist.');
    }
    
}
