<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rawmaterial extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rawmaterial_model');
        $this->load->model('Type_model');
    } 

    /*
     * Listing of rawmaterial
     */
    function index()
    {
        if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('read',$id)&&($this->User_model->hasPermission('rawMaterial',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$id = $this->auth->userid();
			$user = $this->User_model->get('person_id', $id);
			unset($user['password']);
			
			$user_role = $this->User_model->loadRoles($user['person_id']);
					$this->data['user'] = $user['username'];
					$this->data['role'] = $user_role;
					$specialPerm =  $this->User_model->loadSpecialPermission($id);
					
					$this->data['pp'] = $specialPerm;
					$this->data['rawmaterial'] = $this->Rawmaterial_model->get_all_rawmaterial();
					$this->data['type'] = $this->Type_model->get_all_type();
					$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
					
			$this->template
					->title('Welcome','My Aapp')
					->build('rawmaterial/index',$this->data);
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    }

    /*
     * Adding a new rawmaterial
     */
    function add()
    {   
		 if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('add',$id)&&($this->User_model->hasPermission('rawMaterial',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$this->form_validation->set_rules('name', '<b>Name</b>', 'trim|required|max_length[100]');
			$this->form_validation->set_rules('type_id', '<b>Type Id</b>', 'required');
			
			if(isset($_POST) && count($_POST) > 0 && $this->form_validation->run())     
			{   
				$params = array(
					'name' => $this->input->post('name'),
					'type_id' => $this->input->post('type_id'),
				);
				
				$rawmaterial_id = $this->Rawmaterial_model->add_rawmaterial($params);
				redirect('rawmaterial/index');
			}
			else
			{    
				$id = $this->auth->userid();
				$user = $this->User_model->get('person_id', $id);
				unset($user['password']);
				
				$user_role = $this->User_model->loadRoles($user['person_id']);
						$this->data['user'] = $user['username'];
						$this->data['role'] = $user_role;
						$specialPerm =  $this->User_model->loadSpecialPermission($id);
						
						$this->data['pp'] = $specialPerm;
						$this->data['type'] = $this->Type_model->get_all_type();
						$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
						
				$this->template
						->title('Welcome','My Aapp')
						->build('rawmaterial/add',$this->data);
			}
		 
			
		}
		else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
    }  

    /*
     * Editing a rawmaterial
     */
    function edit($mat_id)
    {   
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
				if(!($this->User_model->hasPermission('update',$id)&&($this->User_model->hasPermission('rawMaterial',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
					show_error('You Don\'t have permission to perform this operation.');
					return false;
				}
				// check if the rawmaterial exists before trying to edit it
			$this->data['rawmaterial'] = $this->Rawmaterial_model->get_rawmaterial($mat_id);
			
			if(isset($this->data['rawmaterial']['id']))
			{
				$this->form_validation->set_rules('name', '<b>Name</b>', 'trim|required|max_length[100]');
				$this->form_validation->set_rules('type_id', '<b>Type Id</b>', 'required');
				
				if(isset($_POST) && count($_POST) > 0 && $this->form_validation->run())        
				{   
					$params = array(
						'name' => $this->input->post('name'),
						'type_id' => $this->input->post('type_id'),
					);

					$this->Rawmaterial_model->update_rawmaterial($mat_id,$params);            
					redirect('rawmaterial/index');
				}
				else
				{
					$id = $this->auth->userid();
					$user = $this->User_model->get('person_id', $id);
					unset($user['password']);
					
					$user_role = $this->User_model->loadRoles($user['person_id']);
							$this->data['user'] = $user['username'];
							$this->data['role'] = $user_role;
							$specialPerm =  $this->User_model->loadSpecialPermission($id);
							
							$this->data['pp'] = $specialPerm;
							$this->data['type'] = $this->Type_model->get_all_type();
							$this->data['p_role'] = $this->Person_role_model->get_person_role($id);
		
					$this->template
						->title('Welcome','My Aapp')
						->build('rawmaterial/edit',$this->data);
				}
			}
			else
				show_error('The rawmaterial you are trying to edit does not exist.');
		}else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
        
    } 

    /*
     * Deleting rawmaterial
     */
    function remove($mat_id)
    {
		if ($this->auth->loggedin()) {
			$id = $this->auth->userid();
			if(!($this->User_model->hasPermission('delete',$id)&&($this->User_model->hasPermission('rawMaterial',$id)||$this->User_model->hasPermission('WILD_CARD',$id)))){
				show_error('You Don\'t have permission to perform this operation.');
				return false;
			}
			$rawmaterial = $this->Rawmaterial_model->get_rawmaterial($mat_id);

			// check if the rawmaterial exists before trying to delete it
			if(isset($rawmaterial['id']))
			{
				$this->Rawmaterial_model->delete_rawmaterial($mat_id);
				redirect('rawmaterial/index');
			}
			else
				show_error('The rawmaterial you are trying to delete does not exist.');
		}else{
			$this->template
					->title('Login Admin','Login Page')
					->set_layout('access')
					->build('access/login');
		}
    }
	
    
}
