<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unit extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Unit_model');
    } 

    /*
     * Listing of units
     */
    function index()
    {
        $data['units'] = $this->Unit_model->get_all_units();
        
        $data['_view'] = 'unit/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new unit
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $unit_id = $this->Unit_model->add_unit($params);
            redirect('unit/index');
        }
        else
        {            
            $data['_view'] = 'unit/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a unit
     */
    function edit($id)
    {   
        // check if the unit exists before trying to edit it
        $data['unit'] = $this->Unit_model->get_unit($id);
        
        if(isset($data['unit']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Unit_model->update_unit($id,$params);            
                redirect('unit/index');
            }
            else
            {
                $data['_view'] = 'unit/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The unit you are trying to edit does not exist.');
    } 

    /*
     * Deleting unit
     */
    function remove($id)
    {
        $unit = $this->Unit_model->get_unit($id);

        // check if the unit exists before trying to delete it
        if(isset($unit['id']))
        {
            $this->Unit_model->delete_unit($id);
            redirect('unit/index');
        }
        else
            show_error('The unit you are trying to delete does not exist.');
    }
    
}
