<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Acc_sales_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sale by id
     */
    function get_sale($id)
    {
        return $this->db->get_where('acc_sales',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all acc_sales
     */
    function get_all_acc_sales()
    {
        $this->db->order_by('location_id', 'asc');
        return $this->db->get('acc_sales')->result_array();
    }
	
	/*
     * Get all acc_sales
     */
    function get_location_acc_sales($location_id)
    {
        $this->db->order_by('date', 'asc');
        return $this->db->get_where('acc_sales',array('location_id'=>$location_id))->result_array();
    }
        
    /*
     * function to add new sale
     */
    function add_sale($params)
    {
		//print_r($params);
		for($i=0;$i<sizeof($params['location_id']);$i++){
			
			$tmp['location_id'] = $params['location_id'][$i];
			$tmp['acc_salesType_id'] = $params['acc_salesType_id'][$i];
			$tmp['date'] = $params['date'];
			$tmp['sale'] = $params['sale'][$i];
			$tmp['remark'] = $params['remark'][$i];
			$this->db->insert('acc_sales',$tmp);
			$this->db->insert_id();
			// echo "<br>**************<br>";
			  print_r($tmp);
		}
		return true;
        // $this->db->insert('acc_sales',$params);
        // return $this->db->insert_id();
    }
    
    /*
     * function to update sale
     */
    function update_sale($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('acc_sales',$params);
    }
    
    /*
     * function to delete sale
     */
    function delete_sale($id)
    {
        return $this->db->delete('acc_sales',array('id'=>$id));
    }
}
