<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Acc_expensesType_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get expense by id
     */
    function get_expenseType($id)
    {
        return $this->db->get_where('acc_expense_types',array('id'=>$id))->row_array();
    } 
	
	/*
     * Get expense subtype by id
     */
    function get_expenseSubtype($id)
    {
        return $this->db->get_where('acc_expense_sub_types',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all expense types
     */
    function get_all_expenseType()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('acc_expense_types')->result_array();
    }
	
	/*
     * Get all expense sub-types
     */
    function get_all_expenseSubtype()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('acc_expense_sub_types')->result_array();
    }
	
	        
    /*
     * function to add new expense
     */
    function add_expenseType($params)
    {
		
        $this->db->insert('acc_expense_types',$params);
        return $this->db->insert_id();
    }
	
	/*
     * function to add new expense Subtype
     */
    function add_expenseSubtype($params)
    {
		
        $this->db->insert('acc_expense_sub_types',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update expense
     */
    function update_expenseType($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('acc_expense_types',$params);
    } 
	
	/*
     * function to update expense subtype
     */
    function update_expenseSubtype($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('acc_expense_sub_types',$params);
    }
    
    /*
     * function to delete expense
     */
    function delete_expenseType($id)
    {
        return $this->db->delete('acc_expense_types',array('id'=>$id));
    }
	
	/*
     * function to delete expense subtype
     */
    function delete_expenseSubtype($id)
    {
        return $this->db->delete('acc_expense_sub_types',array('id'=>$id));
    }
}
