<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Acc_expenses_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get acc_expenses by id
     */
    function get_acc_expenses($id)
    {
        return $this->db->get_where('acc_expenses',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all acc_expenses
     */
    function get_all_acc_expenses()
    {
        $this->db->order_by('location_id', 'desc');
        return $this->db->get('acc_expenses')->result_array();
    }
	/*
     * Get all acc_expenses
     */
    function get_location_acc_expenses($location_id)
    {
        $this->db->order_by('date', 'asc');
        return $this->db->get_where('acc_expenses',array('location_id'=>$location_id))->result_array();
    }
        
    /*
     * function to add new acc_expenses
     */
    function add_acc_expenses($params)
    {
		// $tmp = NULL;
		// print_r($params);
		// echo sizeof($params['rawMaterial_id']);
		for($i=0;$i<sizeof($params['rawMaterial_id']);$i++){
			$tmp['acc_expensesNumber'] = $params['acc_expensesNumber'];
			$tmp['supplier_id'] = $params['supplier_id'];
			$tmp['rawMaterial_id'] = $params['rawMaterial_id'][$i];
			$tmp['order_id'] = $params['order_id'];
			$tmp['quantity'] = $params['quantity'][$i];
			$tmp['unit_id'] = $params['unit_id'][$i];
			$tmp['price'] = $params['price'][$i];
			$tmp['date'] = $params['date'];
			$tmp['location_id'] = $params['location_id'];
			
			$this->db->insert('acc_expenses',$tmp);
			$this->db->insert_id();
			//echo "<br>**************<br>";
			// print_r($tmp);
		}
		return true;
		
        //$this->db->insert('acc_expenses',$params);
       // return $this->db->insert_id();
    }
    
    /*
     * function to update acc_expenses
     */
    function update_acc_expenses($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('acc_expenses',$params);
    }
    
    /*
     * function to delete acc_expenses
     */
    function delete_acc_expenses($id)
    {
        return $this->db->delete('acc_expenses',array('id'=>$id));
    }
}
