<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Division_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get division by id
     */
    function get_division($id)
    {
        return $this->db->get_where('division',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all division
     */
    function get_all_division()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('division')->result_array();
    }
        
    /*
     * function to add new division
     */
    function add_division($params)
    {
        $this->db->insert('division',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update division
     */
    function update_division($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('division',$params);
    }
    
    /*
     * function to delete division
     */
    function delete_division($id)
    {
        return $this->db->delete('division',array('id'=>$id));
    }
}
