<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Location_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get location by id
     */
    function get_location($id)
    {
        return $this->db->get_where('location',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all location
     */
    function get_all_location()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('location')->result_array();
    }
        
    /*
     * function to add new location
     */
    function add_location($params)
    {
        $this->db->insert('location',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update location
     */
    function update_location($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('location',$params);
    }
    
    /*
     * function to delete location
     */
    function delete_location($id)
    {
        return $this->db->delete('location',array('id'=>$id));
    }
}
