<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Order_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get order by id
     */
    function get_order($id)
    {
        return $this->db->get_where('order',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all order
     */
    function get_all_order()
    {
		
        $this->db->order_by('location_id', 'asc');
        return $this->db->get('order')->result_array();
    } 
	/*
     * Get all by location
     */
    function get_location_order($location_id)
    {
		
        $this->db->order_by('location_id', 'asc');
        return $this->db->get_where('order',array('location_id'=>$location_id))->result_array();
    }
        
    /*
     * function to add new order
     */
    function add_order($params)
    {
		for($i=0;$i<sizeof($params['rawMaterial_id']);$i++){
			
			$tmp['rawMaterial_id'] = $params['rawMaterial_id'][$i];
			$tmp['quantity'] = $params['quantity'][$i];
			$tmp['unit_id'] = $params['unit_id'][$i];
			$tmp['date'] = $params['date'];
			$tmp['location_id'] = $params['location_id'];
			
			
			 $this->db->insert('order',$tmp);
			$this->db->insert_id();
			// echo "<br>**************<br>";
			 // print_r($tmp);
		}
       
        return true;
    }
    
    /*
     * function to update order
     */
    function update_order($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('order',$params);
    }
    
    /*
     * function to delete order
     */
    function delete_order($id)
    {
        return $this->db->delete('order',array('id'=>$id));
    }
}
