<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Person_role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get person_role by 
     */
    function get_person_role($id)
    {
        return $this->db->get_where('person',array('person_id'=>$id))->row_array();
    }
        
    /*
     * Get all person_role
     */
    function get_all_person_role()
    {
        $this->db->order_by('person_id', 'desc');
        return $this->db->get('person')->result_array();
    }
        
    /*
     * function to add new person_role
     */
    /*function add_person_role($params)
    {
        $this->db->insert('person',$params);
        return $this->db->insert_id();
    }*/
    
    /*
     * function to update person_role
     */
    function update_person_role($id,$params)
    {
        $this->db->where('person_id',$id);
        return $this->db->update('person',$params);
    }
    
    /*
     * function to delete person_role
     */
   /* function delete_person_role($id)
    {
        return $this->db->delete('person',array('person_id'=>$id));
    }*/
}
