<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Person_permission_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get person_permission by 
     */
    function get_person_permission($)
    {
        return $this->db->get_where('person_permission',array(''=>$))->row_array();
    }
        
    /*
     * Get all person_permission
     */
    function get_all_person_permission()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('person_permission')->result_array();
    }
        
    /*
     * function to add new person_permission
     */
    function add_person_permission($params)
    {
        $this->db->insert('person_permission',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update person_permission
     */
    function update_person_permission($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('person_permission',$params);
    }
    
    /*
     * function to delete person_permission
     */
    function delete_person_permission($)
    {
        return $this->db->delete('person_permission',array(''=>$));
    }
}
