<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Purchase_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get purchase by id
     */
    function get_purchase($id)
    {
        return $this->db->get_where('purchase',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all purchase
     */
    function get_all_purchase()
    {
        $this->db->order_by('location_id', 'desc');
        return $this->db->get('purchase')->result_array();
    }
	/*
     * Get all purchase
     */
    function get_location_purchase($location_id)
    {
        $this->db->order_by('date', 'asc');
        return $this->db->get_where('purchase',array('location_id'=>$location_id))->result_array();
    }
        
    /*
     * function to add new purchase
     */
    function add_purchase($params)
    {
		// $tmp = NULL;
		// print_r($params);
		// echo sizeof($params['rawMaterial_id']);
		for($i=0;$i<sizeof($params['rawMaterial_id']);$i++){
			$tmp['purchaseNumber'] = $params['purchaseNumber'];
			$tmp['supplier_id'] = $params['supplier_id'];
			$tmp['rawMaterial_id'] = $params['rawMaterial_id'][$i];
			$tmp['order_id'] = $params['order_id'];
			$tmp['quantity'] = $params['quantity'][$i];
			$tmp['unit_id'] = $params['unit_id'][$i];
			$tmp['price'] = $params['price'][$i];
			$tmp['date'] = $params['date'];
			$tmp['location_id'] = $params['location_id'];
			
			$this->db->insert('purchase',$tmp);
			$this->db->insert_id();
			//echo "<br>**************<br>";
			// print_r($tmp);
		}
		return true;
		
        //$this->db->insert('purchase',$params);
       // return $this->db->insert_id();
    }
    
    /*
     * function to update purchase
     */
    function update_purchase($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('purchase',$params);
    }
    
    /*
     * function to delete purchase
     */
    function delete_purchase($id)
    {
        return $this->db->delete('purchase',array('id'=>$id));
    }
}
