<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rawmaterial_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rawmaterial by id
     */
    function get_rawmaterial($id)
    {
        return $this->db->get_where('rawmaterial',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all rawmaterial
     */
    function get_all_rawmaterial()
    {
        $this->db->order_by('name', 'asc');
        return $this->db->get('rawmaterial')->result_array();
    }
        
    /*
     * function to add new rawmaterial
     */
    function add_rawmaterial($params)
    {
        $this->db->insert('rawmaterial',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rawmaterial
     */
    function update_rawmaterial($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('rawmaterial',$params);
    }
    
    /*
     * function to delete rawmaterial
     */
    function delete_rawmaterial($id)
    {
        return $this->db->delete('rawmaterial',array('id'=>$id));
    }
}
