<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Role_permission_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get role_permission by 
     */
    function get_role_permission($)
    {
        return $this->db->get_where('role_permission',array(''=>$))->row_array();
    }
        
    /*
     * Get all role_permission
     */
    function get_all_role_permission()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('role_permission')->result_array();
    }
        
    /*
     * function to add new role_permission
     */
    function add_role_permission($params)
    {
        $this->db->insert('role_permission',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update role_permission
     */
    function update_role_permission($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('role_permission',$params);
    }
    
    /*
     * function to delete role_permission
     */
    function delete_role_permission($)
    {
        return $this->db->delete('role_permission',array(''=>$));
    }
}
