<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class SaleType_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sale by id
     */
    function get_saleType($id)
    {
        return $this->db->get_where('salestype',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all sales
     */
    function get_all_saleType()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('salestype')->result_array();
    }
	
	        
    /*
     * function to add new sale
     */
    function add_saleType($params)
    {
		//print_r($params);
		// for($i=0;$i<sizeof($params['product_id']);$i++){
			
			
			// $tmp['product_id'] = $params['product_id'][$i];
			// $tmp['quantity'] = $params['quantity'][$i];
			// $tmp['unit_id'] = $params['unit_id'][$i];
			
			// $tmp['date'] = $params['date'];
			// $tmp['location_id'] = $params['location_id'];
			
			// $this->db->insert('salestype',$tmp);
			// $this->db->insert_id();
			// // echo "<br>**************<br>";
			 // // print_r($tmp);
		// }
		// return true;
        $this->db->insert('salestype',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sale
     */
    function update_saleType($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('salestype',$params);
    }
    
    /*
     * function to delete sale
     */
    function delete_saleType($id)
    {
        return $this->db->delete('salestype',array('id'=>$id));
    }
}
