<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Session_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get session by id
     */
    function get_session($id)
    {
        return $this->db->get_where('sessions',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all sessions
     */
    function get_all_sessions()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('sessions')->result_array();
    }
        
    /*
     * function to add new session
     */
    function add_session($params)
    {
        $this->db->insert('sessions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update session
     */
    function update_session($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('sessions',$params);
    }
    
    /*
     * function to delete session
     */
    function delete_session($id)
    {
        return $this->db->delete('sessions',array('id'=>$id));
    }
}
