<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stock_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get stock by id
     */
    function get_stock($id)
    {
        return $this->db->get_where('stock',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all stock
     */
    function get_all_stock($params)
    {
        // $this->db->order_by('location_id', 'desc');
        // return $this->db->get('stock')->result_array();
		$this->db->where('(date >= "'. $params['opening_date'] . '" and date <= "'. $params['closing_date'] .'" )');
		return $this->db->get('stock')->result_array();
    }
	/*
     * Get stock by location
     */
    function get_location_stock($params)
    {
        // $this->db->order_by('date', 'desc');
        // return $this->db->get_where('stock',array('location_id'=>$location_id))->result_array();
		$this->db->where('(date >= "'. $params['opening_date'] . '" and date <= "'. $params['closing_date'] .'" )and location_id='. $params['location_id']);
		return $this->db->get('stock')->result_array();
    }
	/*
	 * Get latest rate per rawMaterial 
	 */
	 function get_rate_rawMaterial($params)
	 {
		// $this->db->select_max('date');
		// $this->db->order_by('date', 'desc');
		// return $this->db->get_where('purchase',array('rawMaterial_id'=>$rawMaterial_id))->row_array();
		
		$tmp = null;
		$this->db->where('(date >= "'. $params['opening_date'] . '" and date <= "'. $params['closing_date'] .'" )and rawMaterial_id='. $params['rawMaterial_id']);
		$this->db->order_by('date', 'desc');
		
		$tmp = $this->db->get('purchase')->row_array();
		
		if($tmp['price'] == 0)
		{
			$this->db->order_by('date', 'asc');
			return $this->db->get_where('purchase',array('rawMaterial_id'=>$params['rawMaterial_id']))->row_array();
			
		}
		else{
			//echo $tmp['id']." NZ: ".$tmp['price']." <br>";
			return $tmp;
		}
	
	 }
	 
    /*
     * function to add new stock
     */
    function add_stock($params)
    {
       
		//print_r($params);
		for($i=0;$i<sizeof($params['rawMaterial_id']);$i++){
			
			$tmp['rawMaterial_id'] = $params['rawMaterial_id'][$i];
			$tmp['quantity'] = $params['quantity'][$i];
			$tmp['unit_id'] = $params['unit_id'][$i];
			$tmp['date'] = $params['date'];
			$tmp['location_id'] = $params['location_id'];
			
			
			$this->db->insert('stock',$tmp);
			$this->db->insert_id();
			// echo "<br>**************<br>";
			 // print_r($tmp);
		}
		return true;
    }
    
    /*
     * function to update stock
     */
    function update_stock($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('stock',$params);
    }
    
    /*
     * function to delete stock
     */
    function delete_stock($id)
    {
        return $this->db->delete('stock',array('id'=>$id));
    }

}
