<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stock_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get stock by id
     */
    function get_stock($id)
    {
        return $this->db->get_where('stock',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all stock
     */
    function get_all_stock()
    {
        $this->db->order_by('location_id', 'desc');
        return $this->db->get('stock')->result_array();
    }
	/*
     * Get stock by location
     */
    function get_location_stock($location_id)
    {
        $this->db->order_by('date', 'desc');
        return $this->db->get_where('stock',array('location_id'=>$location_id))->result_array();
    }
	/*
	 * Get latest rate per rawMaterial 
	 */
	 function get_rate_rawMaterial($rawMaterial_id)
	 {
		// $this->db->select_max('date');
		$this->db->order_by('date', 'desc');
		return $this->db->get_where('purchase',array('rawMaterial_id'=>$rawMaterial_id))->row_array();
	 }
	 
    /*
     * function to add new stock
     */
    function add_stock($params)
    {
       
		//print_r($params);
		for($i=0;$i<sizeof($params['rawMaterial_id']);$i++){
			
			$tmp['rawMaterial_id'] = $params['rawMaterial_id'][$i];
			$tmp['quantity'] = $params['quantity'][$i];
			$tmp['unit_id'] = $params['unit_id'][$i];
			$tmp['date'] = $params['date'];
			$tmp['location_id'] = $params['location_id'];
			
			
			$this->db->insert('stock',$tmp);
			$this->db->insert_id();
			// echo "<br>**************<br>";
			 // print_r($tmp);
		}
		return true;
    }
    
    /*
     * function to update stock
     */
    function update_stock($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('stock',$params);
    }
    
    /*
     * function to delete stock
     */
    function delete_stock($id)
    {
        return $this->db->delete('stock',array('id'=>$id));
    }

}
