<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Supplier_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get supplier by id
     */
    function get_supplier($id)
    {
        return $this->db->get_where('supplier',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all supplier
     */
    function get_all_status_supplier()
    {
        $this->db->order_by('Created', 'asc');
        return $this->db->get('supplier')->result_array();
    }
	
	/*
	*
	*get all active suppliers
	*/
	function get_all_supplier()
    {
        $this->db->order_by('Created', 'asc');
        return $this->db->get_where('supplier',array('status_id ='=>'1'))->result_array();
    }
        
    /*
     * function to add new supplier
     */
    function add_supplier($params)
    {
        $this->db->insert('supplier',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update supplier
     */
    function update_supplier($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('supplier',$params);
    }
    
    /*
     * function to delete supplier
     */
    function delete_supplier($id,$params)
    {
		$this->db->where('id',$id);
        return $this->db->update('supplier',$params);
        // return $this->db->delete('supplier',array('id'=>$id));
    }
}
