<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unit by id
     */
    function get_unit($id)
    {
        return $this->db->get_where('units',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all units
     */
    function get_all_units()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('units')->result_array();
    }
        
    /*
     * function to add new unit
     */
    function add_unit($params)
    {
        $this->db->insert('units',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unit
     */
    function update_unit($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('units',$params);
    }
    
    /*
     * function to delete unit
     */
    function delete_unit($id)
    {
        return $this->db->delete('units',array('id'=>$id));
    }
}
